apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "cert-manager-csi-driver-spiffe.labels" . | indent 4 }}
  name: {{ include "cert-manager-csi-driver-spiffe.name" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "cert-manager-csi-driver-spiffe.labels" . | indent 4 }}
  name: {{ include "cert-manager-csi-driver-spiffe.name" . }}-approver
